// <auto-generated />
namespace OrderPizza1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paymentMethodAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paymentMethodAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201707101153387_paymentMethodAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
