// <auto-generated />
namespace OrderPizza1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201707060820229_201705151326481_seedPizzaAttributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201707060820229_201705151326481_seedPizzaAttributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201707060906598_201707060820229_201705151326481_seedPizzaAttributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
